import type { Metadata } from 'next'; 
import ClientRootLayout from '@/components/layout/clientRootLayout'; 

export const metadata: Metadata = {
  title: 'Book Management System',
  description: 'Book Management app generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientRootLayout>
      {children}
    </ClientRootLayout>
  );
}