// src/app/layout.tsx
// KHÔNG CÓ 'use client' ở đây! File này là Server Component.

import type { Metadata } from 'next'; // Giữ nguyên import Metadata
// Import Client Layout Component bạn vừa tạo
import ClientRootLayout from '@/components/ui/layout/clientRootLayout'; 

// Định nghĩa metadata ở đây - HOÀN TOÀN HỢP LỆ trong Server Component
export const metadata: Metadata = {
  title: 'Book Management System',
  description: 'Book Management app generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Bọc children bằng ClientRootLayout
    // ClientRootLayout sẽ render trên client và sử dụng usePathname
    <ClientRootLayout>
      {children}
    </ClientRootLayout>
  );
}